# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-15 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='rand_int',
            field=models.IntegerField(default=73),
        ),
    ]
