# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-15 11:58
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160415_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='rand_int',
            field=models.IntegerField(default=accounts.models.rand_int),
        ),
    ]
